### ISSUE TITLE
CSS Transforms for better performance

### ISSUE THREAD

**Issue by g-van-vreckem** [jonom/jquery-focuspoint#21]
Replace 
````javascript
...
hShift = focusOffsetX * -1;
...
vShift = focusOffsetY * -1;
...
image.css('left', hShift + 'px');
image.css('top', vShift + 'px');
````
With
````javascript
...
hShift = focusOffsetX * -100 / scaledImageWidth;
...
vShift = focusOffsetY * -100 / scaledImageHeight;
...
image.css('left', hShift + '%');
image.css('top', vShift + '%');
````
Or for the best performance, according to tweenlight: a combo of translate and translate3d

````javascript
image.css('transform', 'translate(' + hShift + '%, ' + vShift + '%) translate3d(0, 0, 0)');
````
Using % intead of px will avoid to have to adjust the focus during a scaled resizing of the container such as perspective change.

**Comment by jonom** [comment]
I've explored switching to translate in v2 but the disadvantage that brings is that you can't then apply additional transforms (such as scale) to an image easily. So I'm putting this on the shelf for now, but thanks for the input!
