### ISSUE TITLE
Add support for focusing video

### ISSUE THREAD

**Issue by g-van-vreckem** [jonom/jquery-focuspoint#30]
see #28 9567f69
Looks simple no?
However:
- The jQuery 'or' selector overhead for 'img, video' seems wasteful.
- It's of course intended only for video with no controls.
- There are platform issues with transform of videos, it should stick to the no transform path.

So it would probably best to implement that in some other way.
Like using a different class (focuspoint-video) with different defaults

**Comment by fnagel** [comment]
+1 for video support!

**Comment by jonom** [comment]
Possible in v2 (in development)
