### ISSUE TITLE
Bootstrap 3 Compatibility?

### ISSUE THREAD

**Issue by bogacg** [jonom/jquery-focuspoint#40]
I couldn't manage to make it work with Bootstrap 3.
Is it compatible with Bootstrap 3 at all?

Strangely focuspoint div get's 0px height.

Thanks

**Comment by jonom** [comment]
Hi @bogacg, I haven't tested this with Bootstrap 3 but there's no reason it shouldn't work. To use FocusPoint in any context you have to first set a desired height on the image container yourself. FocusPoint then fills the space available with image as best it can. If you don't set a height on the container there will be no space to fill so you won't see any image. Please feel free to re-open this issue if this doesn't solve your problem.

**Comment by bogacg** [comment]
You are right. When I give height to div that's focuspoint class it works as expected.
Thank you.
