### ISSUE TITLE
Using the <picture> element and focuspoint

### ISSUE THREAD

**Issue by gpartington** [jonom/jquery-focuspoint#42]
'm trying to use the element for responsive images with JQuery Focuspoint. This works well on page load, and the image adjusts itself to the container. But when an additional image is loaded on resize the images focuspoint doesn't seems to change.

Is it possible to use these 2 libraries together?

**Comment by jonom** [comment]
Hi, what's the library you're using exactly? I haven't tried this with the picture element but it should work okay, however if you're loading images that are cropped differently you would have to adjust the focuspoint data on the shell and then call adjustfocus() to reposition the image appropriately.

**Comment by jonom** [comment]
The Picture element supports art direction on its own so I don't think it should be used with focuspoint.

**Comment by aubricus** [comment]
A bit of a necro-post, but stumbled on this issue when I became interested to see if v1 works against the picture element. 

I disagree that FocusPoint is rendered useless when applied to the picture element; especially for a fluid, full-width element where creating renditions for every possible width is impractical. 

I created [this gist](https://gist.github.com/aubricus/ce8d0f6bc9b35e91bfa7ed89b2a95660) that outlines my quick-and-dirty solution to this.

It relies on injecting new values via plugin's / jquery's data API. A little hacky for my taste but it gets the job done. I hope it's helpful to anyone who may need to do something similar.
