### ISSUE TITLE
Ignore demo files in bower.json

### ISSUE THREAD

**Issue by Lagerregal** [jonom/jquery-focuspoint#56]
Hey,
can you just add the "demos" directory to the list of ignored files in the bower.json file?
I don't want to host your pretty demo images and examples on my server ;-)
Thanks!

**Comment by jonom** [comment]
Hi @Lagerregal feel free to open a pull request for this

**Comment by Lagerregal** [comment]
Hi, see https://github.com/jonom/jquery-focuspoint/pull/58
