### ISSUE TITLE
use focuspoint with face detection library

### ISSUE THREAD

**Issue by gion** [jonom/jquery-focuspoint#7]
Have you thought about using this lib along with some other face detection libraries out there?  
There is [nude.js](http://www.patrick-wied.at/static/nudejs/), [jquery.facedetection](https://github.com/jaysalvat/jquery.facedetection) and many others libraries and algorithms exist that can be used to detect the most important part of an image.  
I think it would be a nice experiment/feature to use focuspoint to automatically focus to an important part of an image.  
I personally had issues with *"half shown faces"*  on certain resolutions on some of my projects, and I think that this *combo* might be a good solution.

**Comment by ethanclevenger91** [comment]
Did anyone ever build something doing this successfully? It seems the coordinates you pass to focuspoint are a bit different than what facedetection spits out, but I'm sure translating probably isn't all that complicated.

**Comment by jonom** [comment]
Closing this for now as it shouldn't be necessary to modify this plugin to add this feature, devs could use a face detection library of their choice to calculate coords and pass them through to FocusPoint. Note that v2 (in development) uses a different grid system so may be more compatible.

Willing to include an example of above if anyone wants to contribute one.
