### ISSUE TITLE
if an image has exif info, could you use camera focus info as focus point.

### ISSUE THREAD

**Issue by chengchengccc** [jonom/jquery-focuspoint#8]
if an image has exif info, could you use camera focus info as focus point.

**Comment by Paul-Browne** [comment]
.exif doesn't have a "focus point" field. It does however have a Exif.Image.SubjectLocation field, also called the subject area [more info](http://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/subjectarea.html)

this returns either 2, 3 or 4 numbers, with the first 2 always being the X and Y coordinates of the "focal point" 

You would also need the image width and height so you can work out the middle of the picture, and where the "focal point" comes relative to it.

**Comment by jonom** [comment]
I probably won't work on this feature myself but welcome input from other developers. I imagine it might work well to add a separate function like getFocusPointFromExif() which would only be need to called once per image and would calculate and add FocusX and FocusY data properties to the image container.

This approach could be used for other auto-detection methods too, so could have things like getFocusPointFromFaces().

**Comment by RonnyO** [comment]
Would work only if the original image dimensions are also there, so it's possible to fix the provided coordinates if the image was resized. But if it was resized/cropped without preserving aspect ratio, or worse, preserved aspect ratio but changed the subject, it will produce wrong results.

**Comment by eladkarako** [comment]
I can see several improvements to the basic algorithm that provides the crop action,
for manual adjustments of the focal-point/area there is a wonderful plugin for Adobe Lightroom with a very simple UI, that can be replicated as a web-app and to generate an <code>img</code> tag with the <code>data-...</code> entries based on the user-selection <br/>
<img src="http://www.lightroomfocuspointsplugin.com/img/screenshots/large/Screenshot2_H467.jpg" />  <br/>

As for the EXIF data, there is a <em>not too complicated</em> calculation, 
based on the <code>Focal length</code> and <code>CCD Width</code> EXIF-entries as explained in this web-page: http://phototour.cs.washington.edu/focal.html
which allows to narrow-down the <em>in-focus</em>-area of an image,
there are various EXIF-reading programs whom the more professional-user can use <a href="https://sno.phy.queensu.ca/~phil/exiftool/">exiftool</a> but there are also https://github.com/mattiasw/ExifReader and https://github.com/exif-js/exif-js which can be embedded in (another?) simple web-app to suggest initial crop-area for an image.

the third, least accurate, method (that can be still be embedded in JS) is a heuristic-method based on analysing group-of-pixels of the entire image, suggesting several candidates where the contrast between pixels is the highest.


One can imagine a web-UI that suggests a manual selection of the focal-area in an image, it then tries to provides best match using the third-method ("heuristic contrast"), replace (improve) with the second method (EXIF data-extraction), 
and leaves it to the user to approve or improve <em>(unintentional rhyme...)</em> the end result.
